### ISSUE TITLE
Runtimes and APIs for perfect compatibility with Windows programs

### ISSUE THREAD

**Issue by gabriellyonnet** [Manily04/Universal-runtime-installer-EN#6]
Add OpenGL, OpenGL ES and Vulkan to this installation ? I want to make sure that the user dont have to do anything other than running a tool like yours to use the computer and that He can directly move to install the programme he wants with no disturb of any kind by an API or runtime installation.

OpenGL : https://www.opengl.org/

OpenGL ES : https://www.khronos.org/api/opengles

Vulkan : https://www.vulkan.org/

You can Alonso Add Winevdm and DOSBox for compatibility with older programs

Winevdm (to run Windows x86 16 bits programs on Windows x86 64 bits) : https://github.com/otya128/winevdm

DOSBox (to run DOS programs on modern computers) : https://www.dosbox.com/

If you see anything more to install to run all programs, make sure to add it. Thanks.

**Comment by Manily04** [comment]
Thanks for the comment.
OpenGL and Vulkan come bundled with your graphics driver and should not be installed with other versions because of compatibility issues with your drivers.
Since Dosbox is an emulator and not a runtime, I will not add it, and Winevdm is basically an emulator too.
What I could do is create another program with SDKs and add more options there.

I hope this helps and you find the tool still useful.
Manily - Marcel
